In [1]:
import numpy as np

In [2]:
a = np.arange(1,3 , dtype = float)
b = np.arange(1,3, dtype = float)
print(a)
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)
print(np.arange(5, dtype=int))
print(np.arange(1,6,2,dtype = int))

[1. 2.]
[[1.]
 [2.]]
(2, 1)
[0 1 2 3 4]
[1 3 5]


In [3]:
print(np.ones((2,3), dtype=float))
print(np.zeros(7,dtype=int))

[[1. 1. 1.]
 [1. 1. 1.]]
[0 0 0 0 0 0 0]


In [4]:
a=np.array([[1,2,3],[4,5,6]], float)
print(np.zeros_like(a)) #이미 있는 원소를 0으로
print(np.ones_like(a)) #이미 있는 원소를 1로

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(np.identity(4,dtype=float)) #4x4의 배열을 대각 1로 채움
print('')
print(np.eye(4, k=1, dtype=float)) #4x4의 배열을 1칸 밀린 대각 1로 채움

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


배열끼리 연산

In [6]:
a = np.arange(1,4, dtype = float)
b = np.array([5,2,6], float)
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(b**a)

[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[  5.   4. 216.]


In [7]:
a = np.array([[1,2],[3,4]], float)
b = np.array([[2,0],[1,3]], float)
print(a*b) #2차원도 연산 가능(열이 맞아야 가능)

[[ 2.  0.]
 [ 3. 12.]]


In [8]:
a = np.array([[1,2],[3,4],[5,6]], float)
b = np.array([-1,3], float)
print(a)
print('')
print(b)
print('')
print(a+b) #열이 맞으면 한 행으로 여러 행 연산 가능

[[1. 2.]
 [3. 4.]
 [5. 6.]]

[-1.  3.]

[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [9]:
a = np.array([1,4,9],float)
print(np.sqrt(a)) # 각 원소의 제곱근 반환

a = np.array([1.1,1.5,1.9], float)
print(np.floor(a)) #내림
print(np.ceil(a)) #올림
print(np.rint(a)) #반올림

print(np.pi) #pi
print(np.e) #자연상수 e

[1. 2. 3.]
[1. 1. 1.]
[2. 2. 2.]
[1. 2. 2.]
3.141592653589793
2.718281828459045


In [10]:
a = np.array([1,4,5], int)
for x in a: #1차원 배열 차례로 출력
    print(x)

1
4
5


In [11]:
a = np.array([[1,2],[3,4],[5,6]], float)
for x in a : #2차원 배열 차례로 출력
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [12]:
a = np.array([[1,2],[3,4],[5,6]], float)
for x, y in a:
    print(x)
    print('')
    print(y)
    print('')
    print(x*y)

1.0

2.0

2.0
3.0

4.0

12.0
5.0

6.0

30.0


In [13]:
a = np.array([2,4,3], float)
print(a.sum()) #전체 합
print(a.prod()) #전체 곱
print(np.sum(a))
print(np.prod(a))

9.0
24.0
9.0
24.0


In [14]:
a = np.array([2,1,9], float)
print(a.mean()) #평균
print(a.var()) #분산
print(a.std()) #표준편차

4.0
12.666666666666666
3.559026084010437


In [15]:
a = np.array([2,1,9], float)
print(a.min()) #최솟값
print(a.max()) #최대값

1.0
9.0


In [16]:
a = np.array([2,1,9], float)
print(a.argmin()) #최소값의 offset
print(a.argmax()) #최대값의 offset

1
2


In [21]:
a=np.array([6,2,5,-1,0], float)
print(sorted(a)) #정렬된 새로운 공간 창출
a.sort()
print(a) #원래 있는 배열을 정렬
print(type(a))

[-1.0, 0.0, 2.0, 5.0, 6.0]
[-1.  0.  2.  5.  6.]
<class 'numpy.ndarray'>


In [23]:
a = np.array([1,3,0],float)
b = np.array([0,3,2], float)

print(a>b)
print(a==b)
print(b>a)

c = a>b
print(c)

a = np.array([1,3,0], float)
print(a>2)

[ True False False]
[False  True False]
[False False  True]
[ True False False]
[False  True False]


In [25]:
c = np.array([True, False, False], bool)

print(any(c)) # 하나라도 True
print(all(c)) # 모두 True

True
False


In [26]:
a = np.array([1,3,0], int)
print(np.logical_and(a>0, a<3)) #모든 조건 부합

b=np.array([True, False, True], bool)
print(np.logical_not(b)) #모든 조건 부정

c = np.array([False, True, False], bool)
print(np.logical_or(b,c)) #같은 열 중 하나라도 참이면

[ True False False]
[False  True False]
[ True  True  True]


In [34]:
a = np.array([1,3,0], float)
print(np.where(a !=0, 6 / a,a)) #0이 아닌 원소는 6/원소, 0인 원소는 그대로
print(np.where(a>0,7,2)) #0보다 큰 원소는 7로, 아닌 원소는 2로 바꾼다

[6. 2. 0.]
[7 7 2]


/home/kur/programming/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [36]:
a = np.array([[0,1],[3,0]],float)
print(a.nonzero()) #원소가 0이면 0으로 출력,0이 아니면 1로 출력

(array([0, 1]), array([1, 0]))


In [43]:
a=np.array([1, np.NaN, np.Inf], float)
print(a)
print(np.isnan(a)) #원소가 숫자가 아닌지 확인
print(np.isfinite(a)) #원소가 무한대가 아닌지 확인

[ 1. nan inf]
[False  True False]
[ True False False]
