In [1]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
range(9)

range(0, 9)

In [10]:
for num in range(9) :
    print(num)

0
1
2
3
4
5
6
7
8


In [14]:
c= np.linspace(0,3,6) #시작점부터 끝까지 같은 크기로 나누어서 배열 생성
print(c)

[0.  0.6 1.2 1.8 2.4 3. ]


In [15]:
d = np.linspace(0,1,5,endpoint=False) #위와 같으나, except endpoint 
print(d)

[0.  0.2 0.4 0.6 0.8]


In [37]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
b = a.reshape(2,5) #이미 생성된 요소를 2x5 배열로 재생성
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
b1 = np.ones(10) #1로 채워진 10크기의 1차원 배열 생성
b2 = np.zeros((5,5)) # 0으로 채워진 5x5 배열 생성
print(b1)
print(b2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


eye(N, M=, k=, dtype=), M은 열 수, k는 대각의 위치(0이 초기값), data type 

In [53]:
np.eye(3,dtype=int) #3차원의 int 타입 대각 배열

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [56]:
np.eye(4,M=7,k=1) #4x7의 1칸 밀린 대각선 배열 dtype = default float

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [61]:
x = np.arange(9).reshape((3,3)) #9칸의 배열을 3x3으로 reshape
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


diag(v,k=0), v는 가져올 array, k는 대각의 위치 (eye()와 다르게 대각에 존재하는 값만을 가져옴)

In [65]:
np.diag(x)

array([0, 4, 8])

In [66]:
np.diag(x,k=1)

array([1, 5])

In [67]:
np.diag(x,k=-1) #x배열의 1칸 당겨진 대각

array([3, 7])

In [68]:
np.diag(np.diag(x)) #eye()와 같은 기능을 함

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [69]:
c = np.empty((2,2)) # garbage값으로 채워진 2x2 array 생성

In [71]:
a = np.array([1,4,5,8],int)
print(a)

[1 4 5 8]


In [72]:
print(a[:2])

[1 4]


In [73]:
print(a[3])

8


In [78]:
a = np.array([[1,2,3],[4,5,6]],int)
print(a)

[[1 2 3]
 [4 5 6]]


In [80]:
print(a[0,0])

1


In [82]:
print(a[1,1])

5


In [136]:
a = np.array([[1,2,3],[4,5,6]],int)
print(a)

[[1 2 3]
 [4 5 6]]


In [156]:
print(a[1,1:])

[5 6]


In [168]:
print(a[:,2])

[3 6]


In [170]:
print(a[-1:,-2:])

[[5 6]]


In [171]:
data = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr = np.array(data)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [173]:
arr[2,:]

array([ 9, 10, 11, 12])

In [177]:
arr[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [189]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [193]:
print(a.shape) # 차원의 크기를 tuple로 표현 2x3
print(data.shape) #list는 표기불가

(2, 3)


AttributeError: 'list' object has no attribute 'shape'

In [198]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [199]:
print(len(a)) # a의 행의 길이

2


In [209]:
a = np.array(range(6),float)
print(a)
b = np.arange(5, dtype=float)
print(b)

[0. 1. 2. 3. 4. 5.]
[0. 1. 2. 3. 4.]


In [210]:
a = a.reshape((2,3)) # 배열 차원 크기 재설정 (값을 전부 포함할 수 있어야 함)
print(a)
print(a.shape)

[[0. 1. 2.]
 [3. 4. 5.]]
(2, 3)


In [215]:
a = np.array([1,2,3], float)
b = a
c = a.copy()
print(a) #같은
print(b) #주소
print(c) #다른 주소

[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]


In [219]:
a = np.array([1,2,3],float)
print(a.tolist())
print(list(a))

[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]


In [220]:
a = np.array([[1,2,3],[4,5,6]],float)
print(a.tolist())
print(list(a))

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
[array([1., 2., 3.]), array([4., 5., 6.])]


In [228]:
a = np.array([1,2,3],float)
s = a.tostring() #a에 저장된 것을 문자열의 주소값 형태로 나타냄
print(s)

print(np.fromstring(s)) #s에 저장된 문자열의 주소값 형태를 해독함

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'
[1. 2. 3.]


/home/kur/programming/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """


In [232]:
a = np.arange(7,dtype=int)
print(a)
a.fill(0) #a 배열의 원소를 0으로 채워넣음
print(a)

[0 1 2 3 4 5 6]
[0 0 0 0 0 0 0]


In [240]:
a = np.array(range(6),float)
print(a)
print('')
a = np.array(range(6),float).reshape((2,3)) # .reshape로 바로 적용 가능
print(a)
print(a[:,1:])

[0. 1. 2. 3. 4. 5.]

[[0. 1. 2.]
 [3. 4. 5.]]
[[1. 2.]
 [4. 5.]]


In [241]:
print(a.transpose()) #row와 column을 reverse

[[0. 3.]
 [1. 4.]
 [2. 5.]]


In [246]:
a = np.array([[1,2,3],[4,5,6]],float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [253]:
print(a.flatten()) #2차원 배열 상태는 유지하지만 flat 상태로 만듦

[1. 2. 3. 4.]


In [257]:
a = np.arange(2, dtype = float)
b = np.array([2,3,4,5], float)
c = np.array([6,7,8], float)
print(np.concatenate((a,b,c))) #가져온 배열들을 이어붙일 수 있다.

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [260]:
a = np.array([[1,2],[3,4]], float)
b = np.array([[5,6],[7,8]], float)
print(np.concatenate((a,b))) #2차원 배열도 붙일 수 있다.
print('\n')
print(np.concatenate((a,b), axis=0))
print('')
print(np.concatenate((a,b), axis=1)) #axis 인자를 주어서 옆으로 이어 붙일 수 있다.

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]

[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [268]:
a = np.array([1,2,3],float)
b = np.array([1,2,3],float)
print(a)
print(a.shape)
print('')
print(a[:,np.newaxis]) # 주 축을 열로 변경
print(a[:,np.newaxis].shape) #행, 열의 크기
print('')
print(b[np.newaxis,:]) # 주 축을 행으로
print(b[np.newaxis,:].shape)

[1. 2. 3.]
(3,)

[[1.]
 [2.]
 [3.]]
(3, 1)

[[1. 2. 3.]]
(1, 3)
