In [5]:
import numpy as np

In [12]:
a = np.arange(1,3 , dtype = float)
b = np.arange(1,3, dtype = float)
print(a)
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)
print(np.arange(5, dtype=int))
print(np.arange(1,6,2,dtype = int))

[1. 2.]
[[1.]
 [2.]]
(2, 1)
[0 1 2 3 4]
[1 3 5]


In [13]:
print(np.ones((2,3), dtype=float))
print(np.zeros(7,dtype=int))

[[1. 1. 1.]
 [1. 1. 1.]]
[0 0 0 0 0 0 0]


In [15]:
a=np.array([[1,2,3],[4,5,6]], float)
print(np.zeros_like(a)) #이미 있는 원소를 0으로
print(np.ones_like(a)) #이미 있는 원소를 1로

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
print(np.identity(4,dtype=float)) #4x4의 배열을 대각 1로 채움
print('')
print(np.eye(4, k=1, dtype=float)) #4x4의 배열을 1칸 밀린 대각 1로 채움

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


배열끼리 연산

In [30]:
a = np.arange(1,4, dtype = float)
b = np.array([5,2,6], float)
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(b**a)

[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[  5.   4. 216.]


In [35]:
a = np.array([[1,2],[3,4]], float)
b = np.array([[2,0],[1,3]], float)
print(a*b) #2차원도 연산 가능(열이 맞아야 가능)

[[ 2.  0.]
 [ 3. 12.]]


In [42]:
a = np.array([[1,2],[3,4],[5,6]], float)
b = np.array([-1,3], float)
print(a)
print('')
print(b)
print('')
print(a+b) #열이 맞으면 한 행으로 여러 행 연산 가능

[[1. 2.]
 [3. 4.]
 [5. 6.]]

[-1.  3.]

[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [48]:
a = np.array([1,4,9],float)
print(np.sqrt(a)) # 각 원소의 제곱근 반환

a = np.array([1.1,1.5,1.9], float)
print(np.floor(a)) #내림
print(np.ceil(a)) #올림
print(np.rint(a)) #반올림

print(np.pi) #pi
print(np.e) #자연상수 e

[1. 2. 3.]
[1. 1. 1.]
[2. 2. 2.]
[1. 2. 2.]
3.141592653589793
2.718281828459045


In [49]:
a = np.array([1,4,5], int)
for x in a: #1차원 배열 차례로 출력
    print(x)

1
4
5


In [50]:
a = np.array([[1,2],[3,4],[5,6]], float)
for x in a : #2차원 배열 차례로 출력
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [52]:
a = np.array([[1,2],[3,4],[5,6]], float)
for x, y in a:
    print(x)
    print('')
    print(y)
    print('')
    print(x*y)

1.0

2.0

2.0
3.0

4.0

12.0
5.0

6.0

30.0


In [56]:
a = np.array([2,4,3], float)
print(a.sum()) #전체 합
print(a.prod()) #전체 곱
print(np.sum(a))
print(np.prod(a))

9.0
24.0
9.0
24.0


In [58]:
a = np.array([2,1,9], float)
print(a.mean()) #평균
print(a.var()) #분산
print(a.std()) #표준편차

4.0
12.666666666666666
3.559026084010437
